//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerMoveTable
    {
        public int PlayerMoveId { get; set; }
        public int GameCode { get; set; }
        public int MoveYX { get; set; }
        public int BackColor { get; set; }
    }
}
